version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    restart: always
    volumes:
      - 'wordpress:/var/www/html'
    networks:
      - inception
    depends_on:
      - mariadb
      - wordpress
    env_file:
      - .env
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/.
    ports: 
      - "9000:9000"
    restart: always
    volumes:
      - 'wordpress:/var/www/html'
    networks:
      - inception
    env_file:
      - .env
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/.
    networks:
      - inception
    volumes:
      - 'mariadb:/var/lib/mysql'
    ports: 
      - "3306:3306"
    restart: always
    env_file:
      - .env

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/hbel-hou/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/hbel-hou/data/mariadb

networks:
  inception: