version: "3"
services:
  nginx:
    build: ./requirements/nginx/.
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - "wordpress:/var/www/html"
    networks:
      - inception
    depends_on:
      - mariadb
      - wordpress
      - ftp
    env_file:
      - .env
  wordpress:
    build: ./requirements/wordpress/.
    image: wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    restart: on-failure
    volumes:
      - "wordpress:/var/www/html"
    networks:
      - inception
    env_file:
      - .env
  mariadb:
    build: ./requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - "mariadb:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: on-failure
    env_file:
      - .env
  adminer:
    build: ./requirements/bonus/adminer/.
    image: adminer
    container_name: adminer
    networks:
      - inception
    ports:
      - "8081:80"
    restart: on-failure
  website:
    build: ./requirements/bonus/website/.
    image: website
    container_name: website
    networks:
      - inception
    ports:
      - "3000:80"
    restart: on-failure
  cadvisor:
    build: ./requirements/bonus/cadvisor/.
    image: cadvisor
    container_name: cadvisor
    networks:
      - inception
    ports:
      - "5000:8080"
    restart: on-failure
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
  redis:
    build: ./requirements/bonus/redis/.
    image: redis
    container_name: redis
    networks:
      - inception
    ports:
      - "6379:6379"
    restart: on-failure
  ftp:
    build: ./requirements/bonus/ftp/.
    image: ftp
    container_name: ftp
    volumes:
      - "wordpress:/home/$FTP_USER/ftp/files"
    networks:
      - inception
    ports:
      - "20-21:20-21"
      - "40000-40005:40000-40005"
    restart: on-failure
    env_file:
      - .env

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: bind
      device: /home/hbel-hou/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: "none"
      o: bind
      device: /home/hbel-hou/data/mariadb

networks:
  inception:
    driver: bridge
